/** icons site
 * http://www.iconfont.cn/collections/detail?spm=a313x.7781069.1998910419.d9df05512&cid=33
 */

export {default as add} from './images/add.png'
export {default as check} from './images/check.png'
export {default as close} from './images/close.png'
export {default as deliver} from './images/deliver.png'
export {default as down} from './images/down.png'
export {default as edit} from './images/edit.png'
export {default as friend} from './images/friend.png'
export {default as goods} from './images/goods.png'
export {default as group} from './images/group.png'
export {default as home} from './images/home.png'
export {default as home_fill} from './images/home_fill.png'
export {default as more} from './images/more.png'
export {default as move}  from './images/move.png'
export {default as my} from './images/my.png'
export {default as my_fill} from './images/my_fill.png'
export {default as notification} from './images/notification.png'
export {default as people} from './images/people.png'
export {default as profile} from './images/profile.png'
export {default as qr_code} from './images/qr_code.png'
export {default as refresh_arrow}   from './images/refresh_arrow.png'
export {default as refund} from './images/refund.png'
export {default as round_check} from './images/round_check.png'
export {default as round_close} from './images/round_close.png'
export {default as scan} from './images/scan.png'
export {default as search} from './images/search.png'
export {default as text} from './images/text.png'
export {default as text_fill} from './images/text_fill.png'
export {default as time} from './images/time.png'
export {default as upload} from './images/upload.png'
export {default as vip} from './images/vip.png'
export {default as write} from './images/write.png'
export {default as present} from './images/present.png'
export {default as present_fill} from './images/present_fill.png'
